# -*- coding: utf-8 -*-
"""Assignment-2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LphmyIY53-9B52E-xSC76B_YXuAhuuap

**EDA**

import pandas liabrary as pd variable 
Pandas library provide with a huge set of important commands and features which are used to easily analyze your data
"""

import pandas as pd

"""Import numpy library as np , NumPy library used for working with arrays. It also has functions for working in domain of linear algebra,
fourier transform, and matrices
"""

import numpy as np

"""To read csv file"""

data = pd.read_csv("Titanic.csv")

"""data is a variable which shows data of csv file  """

data

"""To check total number of rowa and columns in data """

data.shape

"""To know the names of columns"""

data.columns

"""head () returns the first n rows"""

data.head()

"""The tail () function returns last n rows from the data """

data.tail()

"""describe () is used to view some basic statistical details like percentile, mean, std etc. of a data frame """

data.describe()

""" info () function is used to print a concise summary of a DataFrame. This method prints information about a DataFrame including the index dtype and column dtypes, non-null values and memory usage"""

data.info()

"""The isnull () method returns a DataFrame object where all the values are replaced with a Boolean value True for NULL values, and otherwise False. This method takes no parameters."""

data.isnull()

"""notnull ()function detects non-missing values """

data.notnull()

"""dropna () method removes the rows that contains NULL values"""

data.dropna()

"""This is showing the total Number of Null value present in each columns of data 


"""

data.isnull().sum()

"""value_counts() function return a data containing counts of unique values"""

data['Age'].value_counts()

"""DATA VISUALIZATION

Data Visualization is the process of analyzing data in the form of graphs or maps, making it a lot easier to understand the trends or patterns in the data.

import some importent libraries , which help to visualize data importing packages
"""

import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("Titanic.csv")

df

"""to Visualize Pcalss and age on bar graph"""

sns.barplot(x='Pclass',y='Age' ,data=df, )
plt.show()

"""to Visualize Survived on histogram raph"""

sns.histplot(x='Survived' ,data=df, )
plt.show()

"""
to Visualize age vs parch on box raph

"""

df
sns.boxplot( x="Age", y='Parch', data=df)
plt.show()

sns.pairplot(df, hue='Age', height=2)

import missingno as msno

"""to Visualize missing values as a matrix


"""

msno.matrix(df)

""" missingno.heatmap visualizes the correlation matrix about the locations of missing values in columns"""

msno.heatmap(df)

sns.countplot('Survived',data=df)
plt.show()

"""Above graph shows that many people were not survived"""